### PR TITLE
update import map and pin ESM build versions

### PR DESCRIPTION
**Pull request by kwhinnery**
When this template is used without pinned esm.sh builds, it breaks with the following error:

```
kevin@kevin-deno fresh-template-example % deno task start
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 3 routes and 1 islands.
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/*preact-render-to-string@5.2.6
  Lock file: /Users/kevin/dev/denoland/fresh-template-example/deno.lock
```

By pinning the build versions from esm.sh, the project can be run successfully.

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
LGTM

**Review by marvinhagemeister — APPROVED** [review]

**Comment by ayame113** [comment]
Lockfiles were disabled in Fresh v1.1.6, so how about upgrading to 1.1.6?

https://github.com/denoland/fresh/releases#:~:text=refactor%3A%20disable%20lock

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
@ayame113 That also sounds a good idea. Could you send a PR?

**Pull request merged**
